package betterwithmods.common;

import betterwithmods.lib.ModLib;
import net.minecraft.block.Block;
import net.minecraft.block.BlockLiquid;
import net.minecraftforge.fml.common.registry.GameRegistry;


@GameRegistry.ObjectHolder(ModLib.MODID)
public final class BWMBlocks {
    public static final Block ANCHOR = null;
    public static final Block ROPE = null;
    public static final Block FILTERED_HOPPER = null;
    public static final Block MILLSTONE = null;
    public static final Block TURNTABLE = null;
    public static final Block PULLEY = null;
    public static final Block WOODEN_AXLE = null;
    public static final Block WOODEN_GEARBOX = null;
    public static final Block WOODEN_BROKEN_GEARBOX = null;
    public static final Block WOODEN_CLUTCHBOX = null;
    public static final Block WOODEN_BROKEN_CLUTCHBOX = null;
    public static final Block HAND_CRANK = null;
    public static final Block WICKER = null;
    public static final Block URN = null;
    public static final Block SOUL_URN = null;
    public static final Block STOKED_FLAME = null;
    public static final Block HIBACHI = null;
    public static final Block BELLOWS = null;
    public static final Block KILN = null;
    public static final Block HEMP = null;
    public static final Block DETECTOR = null;
    public static final Block LENS = null;
    public static final Block LIGHT_SOURCE = null;
    public static final Block SAW = null;
    public static final Block BOOSTER = null;
    public static final Block HORIZONTAL_WINDMILL = null;
    public static final Block VERTICAL_WINDMILL = null;
    public static final Block WATERWHEEL = null;
    public static final Block WOLF = null;
    public static final Block BLOCK_DISPENSER = null;
    public static final Block BUDDY_BLOCK = null;
    public static final Block CREATIVE_GENERATOR = null;
    public static final Block LIGHT = null;
    public static final Block PLATFORM = null;
    public static final Block MINING_CHARGE = null;
    public static final Block FERTILE_FARMLAND = null;
    public static final Block PUMP = null;
    public static final Block VINE_TRAP = null;
    public static final BlockLiquid TEMP_LIQUID_SOURCE = null;
    public static final Block STEEL_ANVIL = null;
    public static final Block DIRT_SLAB = null;
    public static final Block CRUCIBLE = null;
    public static final Block CAULDRON = null;
    public static final Block DRAGON_VESSEL = null;
    public static final Block IRON_WALL = null;
    public static final Block STAKE = null;
    public static final Block STAKE_STRING = null;
    public static final Block NETHER_GROWTH = null;
    public static final Block STEEL_BLOCK = null;
    public static final Block BLOOD_LOG = null;
    public static final Block BLOOD_LEAVES = null;
    public static final Block BLOOD_SAPLING = null;
    public static final Block NETHER_CLAY = null;
    public static final Block STEEL_PRESSURE_PLATE = null;
    public static final Block INFERNAL_ENCHANTER = null;
    public static final Block CANDLE_HOLDER = null;
    public static final Block SHAFT = null;
    public static final Block BUCKET = null;
    public static final Block BARREL = null;
    public static final Block DETECTOR_RAIL_STONE = null;
    public static final Block DETECTOR_RAIL_STEEL = null;
}
